formatter: "" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  # enabled: true
  # path: modules|aws
  include-main: false

sections:
  hide: []
  show: []

content: |-
  {{ .Requirements }}

  ## Usage

  Basic usage of this module is as follows:

  ```hcl
  module "example" {
  {{"\t"}}source = "<module-path>"
  {{- if .Module.RequiredInputs }}

  {{"\t"}}# Required variables
  {{- range .Module.RequiredInputs }}
  {{- if .GetValue }}
  {{"\t"}}{{ .Name }} = {{ .GetValue | printf "%s" }}
  {{- else }}
  {{"\t"}}{{ .Name }} = <no default>
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Module.OptionalInputs }}

  {{"\t"}}# Optional variables
  {{- range .Module.OptionalInputs }}
  {{- if .GetValue }}
  {{"\t"}}{{ .Name }} = {{ .GetValue | printf "%s" }}
  {{- else }}
  {{"\t"}}{{ .Name }} = <no default>
  {{- end }}
  {{- end }}
  {{- end }}
  }
  ```

  {{ .Resources }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
