# preserve_directory_names: true

ignore: "*.hidden.md"

sort:
  direction: asc
  type: natural
  by: title
  sections: first
  ignore_case: true

append_unmatched: true

nav:
  - "Home":
    - index.md
    - "*"
    - "Tag Glossary": tags.md
  - "Getting Started": getting-started/
  - "User Guide": user-guide/
  - "Internal Guides": guides/
  # - "Other Resources":
  #   - "Code Snippets": code-snippets/
  #   - "*"
  - "Client Knowledge Base": clients/
