name: CI

# Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#filter-pattern-cheat-sheet
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'docs/**'
  #     - 'mkdocs/**'
  #     - 'README.md'
  workflow_dispatch:

jobs:
  conventional-commits:
    name: Validate Conventional Commits
    uses: ./.github/workflows/conventional-commits.yaml

  release:
    name: Release
    uses: ./.github/workflows/release.yaml
    needs: [conventional-commits]

  mkdocs:
    name: Publish Docs to GitHub Pages
    uses: ./.github/workflows/mkdocs.yaml
    needs: [release]
