name: CI

on:
  workflow_dispatch:

jobs:
  conventional-commits:
    name: Validate Conventional Commits
    uses: ./.github/workflows/conventional-commits.yaml

  release:
    name: Release
    uses: ./.github/workflows/release.yaml
    secrets:
      token: ${{ secrets.GH_PAT }}
    needs: [conventional-commits]

  mkdocs:
    name: Publish Docs to GitHub Pages
    uses: ./.github/workflows/mkdocs.yaml
    needs: [release]
