name: CI

# Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#filter-pattern-cheat-sheet
on:
  push:
    branches:
      - main
    # paths:
    #   - 'docs/**'
    #   - 'mkdocs/**'
    #   - 'README.md'
    #   - '.github/workflows/mkdocs.yaml'

env:
  MIN_COMMIT_COUNT_FOR_NO_PR_PUBLISH: -1

jobs:
  init:
    name: Set ENV Outputs
    runs-on: ubuntu-latest
    outputs:
      min-commit-count: ${{ steps.set-outputs.outputs.min_commit_count }}
    steps:
      - name: Set outputs
        id: set-outputs
        run: |
          echo "min_commit_count=${MIN_COMMIT_COUNT_FOR_NO_PR_PUBLISH:-0}" >> $GITHUB_OUTPUT

  conventional-commits:
    name: Validate Conventional Commits
    uses: ./.github/workflows/conventional-commits.yaml

  # mkdocs:
  #   name: Publish Docs to GitHub Pages
  #   uses: ./.github/workflows/mkdocs.yaml
  #   needs: [init, conventional-commits]
  #   if: (needs.conventional-commits.outputs.commit-count > needs.init.outputs.min-commit-count && needs.conventional-commits.outputs.is-merge != 'true') || needs.conventional-commits.outputs.is-merge == 'true'

  release:
    name: Release
    uses: ./.github/workflows/release.yaml
    # needs: mkdocs
