name: PR Checks (Conventional Commits)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # paths:
    #   - 'docs/**'
    #   - 'mkdocs/**'
    #   - 'README.md'
    #   - '.github/workflows/mkdocs.yaml'

jobs:
  conventional-commits:
    name: Check Conventional Commits
    uses: ./.github/workflows/conventional-commits.yaml
