name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**'
      - 'mkdocs/**'
      - 'README.md'
      - '.github/workflows/mkdocs.yaml'

jobs:
  conventional-commits:
    name: Check Conventional Commits
    uses: ./.github/workflows/conventional-commits.yaml
    with:
      base-ref: 'origin/${{ github.event.repository.default_branch }}'
      types: 'feat,fix,docs,style,refactor,perf,test,build,ci,chore,revert'
