name: Release

# Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#filter-pattern-cheat-sheet
on:
  push:
    branches:
      - main
  #   paths:
  #     - 'docs/**'
  #     - 'mkdocs/**'
  #     - 'README.md'

# permissions:
#   contents: write
#   issues: write
#   pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}  # Use PAT instead of GITHUB_TOKEN

      - name: Run semantic release
        uses: ./.github/actions/semantic-release
        with:
          github-token: ${{ secrets.GH_PAT }}  # Use PAT instead of GITHUB_TOKEN
          allow-initial-development-versions: true
          force-bump-patch-version: false
          changelog-generator-opt: "emojis=true"
          prerelease: true
