name: Release

# Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#filter-pattern-cheat-sheet
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'docs/**'
  #     - 'mkdocs/**'
  #     - 'README.md'
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
  workflow_call:
    inputs:
      workflow_call:
        description: 'To distinguish workflow_call from push'
        type: boolean
        required: false
        default: false
      fail-on-no-release:
        description: 'Whether to fail the workflow if no release is to be published'
        type: boolean
        required: false
        default: false

# permissions:
#   contents: write
#   issues: write
#   pull-requests: write

jobs:
  release:
    if: inputs.workflow_call || github.event_name == 'push'

    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run semantic release
        uses: ./.github/actions/semantic-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: false
          changelog-generator-opt: "emojis=true"
          fail-on-no-release: ${{ inputs.fail-on-no-release }}
          prerelease: true
