name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

# permissions:
#   contents: write
#   issues: write
#   pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        uses: go-semantic-release/action@v1
        id: semantic-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: false
          changelog-generator-opt: "emojis=true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show changelog
        if: steps.semantic-release.outputs.version != ''
        run: |
          echo "Changelog: ${{ steps.semantic-release.outputs.changelog }}"

      - name: Show release information
        if: steps.semantic-release.outputs.version != ''
        run: |
          echo "✅ Released version: ${{ steps.semantic-release.outputs.version }}"
          echo "🔗 Release URL: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ steps.semantic-release.outputs.version }}"
